#!/usr/bin/env python3
import sys
import asyncio
sys.path.insert(0, "/usr/lib/python3/dist-packages")  

from pypolicyd.smtp_policy_daemon import main

if __name__ == "__main__":
    asyncio.run(main())
